version: '3.3'
services:
  post_db:
    image: mongo:latest
    container_name: mongo-log
    volumes:
      - post_db:${DB_PATH}
    networks:
      common_net:
        aliases:
          - comment_db
          - post_db

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    container_name: ui-log
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - common_net

  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    container_name: post-log
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      common_net:
        aliases:
          - post

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    container_name: comment-log
    networks:
      common_net:
        aliases:
          - comment

volumes:
  post_db:
  prometheus_data:

networks:
  common_net:
