FROM ruby:2.2-alpine

RUN apk add --no-cache --update build-base
RUN gem install bundler -v "1.17.3" --no-document

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN bundle install
ADD . $APP_HOME

ENV COMMENT_DATABASE_HOST comment_db_host
ENV COMMENT_DATABASE comments

CMD ["puma"]
