version: '3.3'
services:
  post_db:
    image: mongo:latest
    container_name: mongo
    volumes:
      - post_db:${DB_PATH}
    networks:
      front_net:
        aliases:
          - comment_db_host
          - post_db_host

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    container_name: ui
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
      - back_net

  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    container_name: post
    networks:
      front_net:
        aliases:
          - post_host
      back_net:
        aliases:
          - post_host

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    container_name: comment
    networks:
      front_net:
        aliases:
          - comment_host
      back_net:
        aliases:
          - comment_host

volumes:
  post_db:

networks:
  front_net:
  back_net:
