version: '3.3'
services:
  post_db:
    image: mongo:latest
    container_name: mongo
    volumes:
      - post_db:${DB_PATH}
    networks:
      common_net:
        aliases:
          - comment_db_host
          - post_db_host

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    container_name: ui
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - common_net

  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    container_name: post
    networks:
      common_net:
        aliases:
          - post_host

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    container_name: comment
    networks:
      common_net:
        aliases:
          - comment_host

  prometheus:
          image: ${USERNAME}/prometheus:${PROMETHEUS_VERSION}
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - common_net

volumes:
  prometheus_data:

volumes:
  post_db:

networks:
  front_net:
  back_net:
